export const INDUSTRY_OPTIONS = [
  { value: '', label: 'Select an industry' },
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Advertising & Marketing', label: 'Advertising & Marketing' },
  { value: 'Agriculture', label: 'Agriculture' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Aviation / Aerospace', label: 'Aviation / Aerospace' },
  { value: 'Banking & Financial Services', label: 'Banking & Financial Services' },
  { value: 'Biotechnology', label: 'Biotechnology' },
  { value: 'Construction', label: 'Construction' },
  { value: 'Consulting', label: 'Consulting' },
  { value: 'Consumer Goods / FMCG', label: 'Consumer Goods / FMCG' },
  { value: 'Education', label: 'Education' },
  { value: 'E-commerce', label: 'E-commerce' },
  { value: 'Electronics', label: 'Electronics' },
  { value: 'Energy / Oil & Gas', label: 'Energy / Oil & Gas' },
  { value: 'Energy / Utilities', label: 'Energy / Utilities' },
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Entertainment & Media', label: 'Entertainment & Media' },
  { value: 'Fashion & Apparel', label: 'Fashion & Apparel' },
  { value: 'Food & Beverage', label: 'Food & Beverage' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Hospitality & Tourism', label: 'Hospitality & Tourism' },
  { value: 'Insurance', label: 'Insurance' },
  { value: 'Internet / Online Services', label: 'Internet / Online Services' },
  { value: 'Legal Services', label: 'Legal Services' },
  { value: 'Logistics & Supply Chain', label: 'Logistics & Supply Chain' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Non-Profit / NGO', label: 'Non-Profit / NGO' },
  { value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'Real Estate', label: 'Real Estate' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Software / SaaS', label: 'Software / SaaS' },
  { value: 'Telecommunications', label: 'Telecommunications' },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Other', label: 'Other' },
];
